name: Pulumi Deployment
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'infra/**'
      - '.github/workflows/pulumi-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      secrets: read
      id-token: write  # Required for GitHub OIDC auth

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Pulumi
        uses: pulumi/actions@v4
        with:
          pulumi-version: '3.100.0'

      - name: Configure Pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.ORG_PULUMI_ACCESS_TOKEN }}
          PULUMI_CONFIGURE_PASSPHRASE: ${{ secrets.PULUMI_CONFIGURE_PASSPHRASE }}
        run: |
          pulumi login
          pulumi stack select dev

      - name: Install dependencies
        working-directory: ./infra
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pulumi
        working-directory: ./infra
        env:
          ORG_DIGITALOCEAN_TOKEN: ${{ secrets.ORG_DIGITALOCEAN_TOKEN }}
          ORG_MONGODB_ORG_ID: ${{ secrets.ORG_MONGODB_ORG_ID }}
          ORG_MONGODB_API_PUBLIC_KEY: ${{ secrets.ORG_MONGODB_API_PUBLIC_KEY }}
          ORG_MONGODB_API_PRIVATE_KEY: ${{ secrets.ORG_MONGODB_API_PRIVATE_KEY }}
          ORG_OPENAI_API_KEY: ${{ secrets.ORG_OPENAI_API_KEY }}
        run: |
          ./populate_pulumi_secrets.sh
          pulumi up --yes --refresh
