"""
"""
    """Base exception for all conductor errors."""
    """Raised when there's a configuration issue."""
    """Raised when a required dependency is missing or unavailable."""
    """Base exception for memory system errors."""
    """Raised when a connection to a memory storage system fails."""
    """Raised when a memory operation fails."""
    """Raised when a memory item is not found."""
    """Base exception for agent-related errors."""
    """Raised when a requested agent is not found."""
    """Raised when an agent execution fails."""
    """Base exception for resilience system errors."""
    """Raised when a circuit breaker is open."""
    """Raised when a fallback operation fails."""
    """Base exception for LLM-related errors."""
    """Raised when an LLM provider operation fails."""
    """Raised when an LLM provider enforces rate limiting."""
    """Base exception for API-related errors."""
    """Raised when API request validation fails."""
    """Raised when a required service is unavailable."""