name: Validate Secret Manager Configuration

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [main, develop]
    paths:
      - 'infra/modules/secret-manager/**'
      - 'infra/orchestra-terraform/secrets.tf'
  pull_request:
    branches: [main, develop]
    paths:
      - 'infra/modules/secret-manager/**'
      - 'infra/orchestra-terraform/secrets.tf'

jobs:
  validate-secrets:
    name: Validate Secret Manager Configuration
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        environment: [dev, prod]
        service: [orchestra-api]
      fail-fast: false  # Continue with other environments if one fails
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-cloud-secretmanager
      
      - name: Run Terraform validation
        working-directory: ${{ github.workspace }}/infra/modules/secret-manager
        run: |
          echo "Validating Terraform files for syntax errors"
          # Use TFLint or Terraform validate if available
          # tfvalidate .
          
      - name: Validate environment configuration
        working-directory: ${{ github.workspace }}/infra/modules/secret-manager/validation
        run: |
          echo "Validating environment separation for ${{ matrix.environment }}"
          python3 test_env_config.py
      
      # Only run this step if GCP credentials are provided
      - name: Authenticate to Google Cloud
        id: auth
        if: ${{ env.SKIP_GCP_AUTH != 'true' }}
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
        continue-on-error: true
      
      - name: Set up gcloud CLI
        if: steps.auth.outcome == 'success'
        uses: google-github-actions/setup-gcloud@v1

      - name: Validate Secret Manager Configuration
        if: steps.auth.outcome == 'success'
        run: |
          cd infra/modules/secret-manager/validation
          chmod +x run_validation.sh
          ./run_validation.sh ${{ secrets.GCP_PROJECT_ID }} ${{ matrix.environment }} ${{ matrix.service }}
      
      - name: Skip Secret Manager validation
        if: steps.auth.outcome != 'success'
        run: |
          echo "::warning::Skipping live Secret Manager validation because GCP authentication failed or was skipped"
          echo "To enable live validation, add GCP_SA_KEY and GCP_PROJECT_ID secrets to your GitHub repository"
      
      - name: Notify on Failure
        if: failure()
        run: |
          echo "::error::Secret Manager validation failed for ${{ matrix.environment }} environment!"