version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "scoobyjava"
    assignees:
      - "scoobyjava"
    commit-message:
      prefix: "deps"
      include: "scope"
    # Auto-merge low-risk updates
    allow:
      - dependency-type: "direct"
        update-type: "version-update:semver-patch"
      - dependency-type: "indirect"
        update-type: "version-update:semver-patch"
    
  # Python requirements in subdirectories
  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "daily"
      time: "09:30"
    open-pull-requests-limit: 3
    reviewers:
      - "scoobyjava"
    assignees:
      - "scoobyjava"
    commit-message:
      prefix: "deps(requirements)"
      include: "scope"
    
  # Node.js dependencies (admin-ui)
  - package-ecosystem: "npm"
    directory: "/admin-ui"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 3
    reviewers:
      - "scoobyjava"
    assignees:
      - "scoobyjava"
    commit-message:
      prefix: "deps(admin-ui)"
      include: "scope"
    # Auto-merge patch updates for admin-ui
    allow:
      - dependency-type: "direct"
        update-type: "version-update:semver-patch"
      - dependency-type: "indirect"
        update-type: "version-update:semver-patch"
        
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 2
    reviewers:
      - "scoobyjava"
    assignees:
      - "scoobyjava"
    commit-message:
      prefix: "deps(actions)"

