version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "America/Los_Angeles"
    commit-message:
      prefix: "ci"
      include: "scope"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/Los_Angeles"
    commit-message:
      prefix: "security"
      prefix-development: "deps-dev"
      include: "scope"
    open-pull-requests-limit: 15
    reviewers:
      - "scoobyjava"
    assignees:
      - "scoobyjava"
    allow:
      - dependency-type: "all"
    groups:
      security-updates:
        applies-to: security-updates
        patterns: ["*"]

  - package-ecosystem: "npm"
    directory: "/admin-interface"
    schedule:
      interval: "weekly"
      time: "10:00"
      timezone: "America/Los_Angeles"
    commit-message:
      prefix: "deps-frontend"
      include: "scope"
    open-pull-requests-limit: 10
    reviewers:
      - "scoobyjava"
    assignees:
      - "scoobyjava"
    
  - package-ecosystem: "npm"  
    directory: "/dashboard"
    schedule:
      interval: "weekly"
      time: "10:00"
      timezone: "America/Los_Angeles"
    commit-message:
      prefix: "deps-dashboard"
      include: "scope"
    open-pull-requests-limit: 10
    reviewers:
      - "scoobyjava"
    assignees:
      - "scoobyjava"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker"
      include: "scope"
    open-pull-requests-limit: 5

