# Dependabot configuration for AI Orchestra project
# Automatically updates dependencies to address security vulnerabilities

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "docker"
      include: "scope"

  # Node.js (Admin UI)
  - package-ecosystem: "npm"
    directory: "/admin-ui"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
      - "admin-ui"
    commit-message:
      prefix: "deps"
      include: "scope"
