# Dependabot configuration for AI cherry_ai project
# Automatically updates dependencies to address security vulnerabilities
# Updated: 2025-06-02 - Enhanced for comprehensive security scanning

version: 2
updates:
  # Python dependencies - Base requirements
  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "daily"  # Check daily for security updates
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
      - "python"
    commit-message:
      prefix: "deps"
      include: "scope"
    # Prioritize security updates
    priority: 1
    groups:
      python-security:
        patterns:
          - "*"
        update-types:
          - "security"

  # Python dependencies - Root directory
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "security"
      - "python"
    commit-message:
      prefix: "deps"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "docker"
      include: "scope"

  # Node.js (Admin UI)
  - package-ecosystem: "npm"
    directory: "/admin-ui"
    schedule:
      interval: "daily"  # Daily for security
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
      - "admin-ui"
    commit-message:
      prefix: "deps"
      include: "scope"
    # Group security updates
    groups:
      npm-security:
        patterns:
          - "*"
        update-types:
          - "security"
