# Secret scanning configuration for AI Orchestra project
# This file configures GitHub's secret scanning to ignore false positives

# Paths to exclude from secret scanning
paths:
  - "track_migration_progress.sh"  # This file contains no actual secrets, only secure methods to retrieve them

# Patterns to exclude (optional)
patterns:
  - pattern: "gcloud secrets (describe|versions access)"
    description: "gcloud CLI commands for Secret Manager operations"
    justification: "These are commands to securely retrieve secrets, not the secrets themselves"