name: Infrastructure Sync

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  sync-infrastructure:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION || 'us-central1' }}
      ENV: ${{ github.event.inputs.environment }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-cloud-secret-manager google-cloud-storage google-api-python-client

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: 'gke-gcloud-auth-plugin'

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Run Infrastructure Setup
        run: |
          chmod +x ./setup_gcp_infrastructure.sh
          ./setup_gcp_infrastructure.sh

      - name: Verify GCP Setup
        run: |
          chmod +x ./scripts/verify_gcp_setup.sh
          ./scripts/verify_gcp_setup.sh

      - name: Update GitHub Secrets
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
        run: |
          chmod +x ./scripts/update_github_org_secrets.sh
          ./scripts/update_github_org_secrets.sh

      - name: Update Codespaces Secrets
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
        run: |
          chmod +x ./scripts/update_codespaces_secrets.sh
          ./scripts/update_codespaces_secrets.sh