repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=500']  # Match with LFS threshold in automation config
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.262
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: local
    hooks:
      - id: gemini-code-analysis
        name: Gemini Code Analysis
        entry: python analyze_code_wrapper.py
        language: system
        pass_filenames: false
        stages: [commit]
        verbose: true

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies: [
          'types-requests',
          'types-PyYAML'
        ]
        # Specify files to avoid running on entire codebase
        files: >
          (?x)(
            automation_controller\.py|
            fully_automated_performance_enhancement\.py|
            workspace_optimization\.py|
            automation_decision_helper\.py|
            analyze_code_wrapper\.py
          )
