---
# Phase 1: YAML linting configuration
extends: default

rules:
  line-length:
    max: 120
    level: warning
  comments:
    min-spaces-from-content: 2
  indentation:
    spaces: 2
    indent-sequences: true
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']

ignore: |
  .git/
  node_modules/
  .venv/
  venv/
  legacy/
  archive/ 