#!/bin/bash
echo "🚀 FINAL deployment of REAL agents to cherry-ai.me"
echo "Password required: z+G3D,$n9M3.=Dr}"
echo ""
echo "Run these commands on your server:"
echo "========================================"
echo ""
echo "ssh root@45.32.69.157"
echo ""
echo "# Once logged in, run:"
echo "cd /opt/cherry_ai"
echo "pkill -f uvicorn"
echo "cd /root/cherry_ai-main"
echo "source venv/bin/activate"
echo ""
echo "# Test real agents work:"
echo "python test_real_agents.py"
echo ""
echo "# Start REAL API:"
echo "nohup python -m uvicorn agent.app.main:app --host 0.0.0.0 --port 8000 > /root/api_real.log 2>&1 &"
echo "sleep 3"
echo ""
echo "# Test it's working:"
echo "curl -X GET 'http://localhost:8000/api/agents' -H 'X-API-Key: 4010007a9aa5443fc717b54e1fd7a463260965ec9e2fce297280cf86f1b3a4bd' | jq '.'"
echo ""
echo "========================================"
echo ""
echo "Then visit https://cherry-ai.me and you'll see:"
echo "- sys-001: System Monitor (shows REAL CPU/memory)"
echo "- analyze-001: Data Analyzer (does REAL analysis)"
echo "- monitor-001: Service Monitor (REAL monitoring)"
