version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped

  mcp_server:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    ports:
      - "8003:8003"
    volumes:
      - .:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  database-data:

