FROM hashicorp/terraform:1.5.0

RUN apk add --no-cache bash curl jq python3

# Install Google Cloud SDK
RUN curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-linux-x86_64.tar.gz &&     tar -xf google-cloud-cli-linux-x86_64.tar.gz &&     ./google-cloud-sdk/install.sh --quiet &&     rm google-cloud-cli-linux-x86_64.tar.gz

ENV PATH=$PATH:/google-cloud-sdk/bin

WORKDIR /workspace
