services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8001
    container_name: cherry_ai_api
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      weaviate:
        condition: service_started
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      REDIS_URL: ${REDIS_URL}
      WEAVIATE_URL: ${WEAVIATE_URL}
    ports:
    - 8001:8001
    restart: unless-stopped
  postgres:
    container_name: cherry_ai_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      interval: 10s
      retries: 5
      test:
      - CMD-SHELL
      - pg_isready -U ${POSTGRES_USER}
      timeout: 5s
    image: postgres:15-alpine
    ports:
    - 5432:5432
    restart: unless-stopped
    volumes:
    - postgres_data:/var/lib/postgresql/data
  redis:
    container_name: cherry_ai_redis
    healthcheck:
      interval: 10s
      retries: 5
      test:
      - CMD
      - redis-cli
      - ping
      timeout: 5s
    image: redis:7-alpine
    ports:
    - 6379:6379
    restart: unless-stopped
    volumes:
    - redis_data:/data
  weaviate:
    container_name: cherry_ai_weaviate
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      DEFAULT_VECTORIZER_MODULE: none
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      QUERY_DEFAULTS_LIMIT: 25
    image: semitechnologies/weaviate:latest
    ports:
    - 8081:8080
    restart: unless-stopped
    volumes:
    - weaviate_data:/var/lib/weaviate
version: '3.8'
volumes:
  postgres_data: null
  redis_data: null
  weaviate_data: null
