#!/bin/bash
# Weaviate Fix Script - Generated by debugger

echo "Fixing Weaviate issues..."

# 1. Fix Python syntax errors
echo "Checking for Python syntax errors..."
find /opt/weaviate -name "*.py" -exec python3 -m py_compile {} \; 2>&1 | grep -E "SyntaxError|IndentationError"

# 2. Restart Weaviate service
echo "Restarting Weaviate service..."
sudo systemctl stop weaviate
sleep 2
sudo systemctl start weaviate

# 3. Wait for service to start
echo "Waiting for service to start..."
sleep 10

# 4. Check service status
sudo systemctl status weaviate

# 5. Test API connectivity
echo "Testing API connectivity..."
curl -s http://localhost:8080/v1/.well-known/ready || echo "API not ready"

echo "Fix script completed"
