#!/bin/bash
# ONE COMMAND TO FIX EVERYTHING

echo "Copy this ENTIRE command and run it on your server:"
echo "=================================================="
echo ""
echo 'pkill -f uvicorn; pkill -f orchestra; systemctl stop orchestra-api; systemctl disable orchestra-api; rm -rf /opt/orchestra; cd /root/orchestra-main && source venv/bin/activate && nohup python -m uvicorn agent.app.main:app --host 0.0.0.0 --port 8000 > /root/api_real.log 2>&1 & sleep 5 && echo "✅ REAL AGENTS NOW RUNNING! Mock garbage DELETED!"'
echo ""
echo "=================================================="
echo ""
echo "Or run these step by step:"
echo ""
echo "1. SSH to server: ssh root@45.32.69.157"
echo "   Password: z+G3D,$n9M3.=Dr}"
echo ""
echo "2. Kill old stuff and delete mock:"
echo "   pkill -f uvicorn"
echo "   pkill -f orchestra"
echo "   systemctl stop orchestra-api"
echo "   rm -rf /opt/orchestra"
echo ""
echo "3. Start REAL agents:"
echo "   cd /root/orchestra-main"
echo "   source venv/bin/activate"
echo "   nohup python -m uvicorn agent.app.main:app --host 0.0.0.0 --port 8000 > /root/api_real.log 2>&1 &"
echo ""
echo "4. Test it:"
echo "   curl -X GET 'http://localhost:8000/api/agents' -H 'X-API-Key: 4010007a9aa5443fc717b54e1fd7a463260965ec9e2fce297280cf86f1b3a4bd' | jq '.'"
