#!/bin/bash
# setup_gcp_env.sh
# Script to set up environment variables for GCP configuration

set -e

# Color codes for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Log function
log() {
  local level=$1
  local message=$2
  local timestamp=$(date "+%Y-%m-%d %H:%M:%S")
  
  case $level in
    "INFO")
      echo -e "${BLUE}[${timestamp}] [INFO] ${message}${NC}"
      ;;
    "WARN")
      echo -e "${YELLOW}[${timestamp}] [WARN] ${message}${NC}"
      ;;
    "ERROR")
      echo -e "${RED}[${timestamp}] [ERROR] ${message}${NC}"
      ;;
    "SUCCESS")
      echo -e "${GREEN}[${timestamp}] [SUCCESS] ${message}${NC}"
      ;;
    *)
      echo -e "[${timestamp}] ${message}"
      ;;
  esac
}

# Configuration
PROJECT_ID="cherry-ai-project"
ACCOUNT="scoobyjava@cherry-ai.me"
REGION="us-central1"

# Create or update .env file
log "INFO" "Creating or updating .env file..."
cat > .env << EOF
# Environment variables for AI Orchestra project
# Generated by setup_gcp_env.sh

# GCP settings
PROJECT_ID=${PROJECT_ID}
REGION=${REGION}
ACCOUNT=${ACCOUNT}

# Vertex AI settings
VERTEX_LOCATION=${REGION}

# API settings
API_PREFIX=/api
PORT=8080

# Security settings
CORS_ORIGINS=*

# Logging
LOG_LEVEL=INFO

# Environment
ENVIRONMENT=dev
DEBUG=true

# Google Cloud SDK environment variables
CLOUDSDK_CORE_PROJECT=${PROJECT_ID}
CLOUDSDK_CORE_ACCOUNT=${ACCOUNT}
EOF

# Set environment variables for current session
log "INFO" "Setting environment variables for current session..."
export PROJECT_ID="${PROJECT_ID}"
export REGION="${REGION}"
export ACCOUNT="${ACCOUNT}"
export VERTEX_LOCATION="${REGION}"
export CLOUDSDK_CORE_PROJECT="${PROJECT_ID}"
export CLOUDSDK_CORE_ACCOUNT="${ACCOUNT}"

# Add environment variables to .bashrc if they don't exist
log "INFO" "Adding environment variables to .bashrc..."
if ! grep -q "CLOUDSDK_CORE_PROJECT" ~/.bashrc; then
  echo "export CLOUDSDK_CORE_PROJECT=\"${PROJECT_ID}\"" >> ~/.bashrc
fi

if ! grep -q "CLOUDSDK_CORE_ACCOUNT" ~/.bashrc; then
  echo "export CLOUDSDK_CORE_ACCOUNT=\"${ACCOUNT}\"" >> ~/.bashrc
fi

log "SUCCESS" "Environment variables set up successfully!"
log "INFO" "Project ID: ${PROJECT_ID}"
log "INFO" "Account: ${ACCOUNT}"
log "INFO" "Region: ${REGION}"
log "INFO" "To apply the changes to a new terminal session, run: source ~/.bashrc"