#!/bin/bash
# source_env_and_ensure_gcp.sh
# Script to source environment variables from .env file and ensure GCP environment variables are set correctly

# Color codes for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Log function
log() {
  local level=$1
  local message=$2
  local timestamp=$(date "+%Y-%m-%d %H:%M:%S")
  
  case $level in
    "INFO")
      echo -e "${BLUE}[${timestamp}] [INFO] ${message}${NC}"
      ;;
    "WARN")
      echo -e "${YELLOW}[${timestamp}] [WARN] ${message}${NC}"
      ;;
    "ERROR")
      echo -e "${RED}[${timestamp}] [ERROR] ${message}${NC}"
      ;;
    "SUCCESS")
      echo -e "${GREEN}[${timestamp}] [SUCCESS] ${message}${NC}"
      ;;
    *)
      echo -e "[${timestamp}] ${message}"
      ;;
  esac
}

# Check if .env file exists
if [ -f .env ]; then
  log "INFO" "Sourcing environment variables from .env file..."
  # Source environment variables from .env file
  set -a
  source .env
  set +a
  log "SUCCESS" "Environment variables sourced from .env file!"
else
  log "WARN" ".env file not found. Creating it..."
  
  # Create .env file
  cat > .env << EOF
# Environment variables for AI Orchestra project
# Generated by source_env_and_ensure_gcp.sh

# GCP settings
PROJECT_ID=cherry-ai-project
REGION=us-central1
ACCOUNT=scoobyjava@cherry-ai.me

# Vertex AI settings
VERTEX_LOCATION=us-central1

# API settings
API_PREFIX=/api
PORT=8080

# Security settings
CORS_ORIGINS=*

# Logging
LOG_LEVEL=INFO

# Environment
ENVIRONMENT=dev
DEBUG=true

# Google Cloud SDK environment variables
CLOUDSDK_CORE_PROJECT=cherry-ai-project
CLOUDSDK_CORE_ACCOUNT=scoobyjava@cherry-ai.me
CLOUDSDK_CORE_REGION=us-central1
CLOUDSDK_CORE_ZONE=us-central1-a
EOF
  
  # Source environment variables from .env file
  set -a
  source .env
  set +a
  log "SUCCESS" ".env file created and environment variables sourced!"
fi

# Run ensure_gcp_env.sh
log "INFO" "Running ensure_gcp_env.sh..."
./ensure_gcp_env.sh

log "SUCCESS" "Environment variables are set correctly!"
log "INFO" "You can now use GCP commands with the following configuration:"
log "INFO" "Project: $CLOUDSDK_CORE_PROJECT"
log "INFO" "Account: $CLOUDSDK_CORE_ACCOUNT"
log "INFO" "Region: $CLOUDSDK_CORE_REGION"
log "INFO" "Zone: $CLOUDSDK_CORE_ZONE"