version: '3.4'
services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.1
    restart: always
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: '20'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: 'text2vec-openai,reranker-openai'
      CLUSTER_HOSTNAME: 'weaviate-node'
      QUERY_DEFAULT_ACORN_ENABLED: 'true'
    volumes:
      - /var/lib/weaviate:/var/lib/weaviate
