config:
  LAMBDA_API_KEY:
    description: Lambda API key for infrastructure management
    secret: true
    type: string
  ssh_public_key:
    description: SSH public key for server access
    type: string
description: Cherry AI Orchestrator Infrastructure
name: cherry-ai-orchestrator
runtime: python
template:
  config:
    Lambda:apiKey:
      secret: true
      type: string
