name: cherry-ai-infrastructure
runtime:
  name: python
  options:
    virtualenv: venv
description: Infrastructure as Code for Cherry-AI.me on Vultr
config:
  vultr:region: ewr  # New Jersey region
  environment: production
