"""
Pydantic models for movie script generation.

These models define the structure of movie scripts that can be generated by
Phidata's StructuredAgent and formatted for display in the Phidata Agent UI.
"""

from typing import List, Optional
from pydantic import BaseModel, Field


class Scene(BaseModel):
    """
    Model representing a scene in a movie script.

    Attributes:
        description: Brief description of the scene
        setting: Location or setting where the scene takes place
        script_content: The actual script content including dialogue and action
    """

    description: str = Field(
        ...,
        description="Brief description of the scene (e.g., 'The protagonist discovers the hidden treasure')",
    )
    setting: str = Field(
        ...,
        description="Location or setting of the scene (e.g., 'INT. ABANDONED WAREHOUSE - NIGHT')",
    )
    script_content: str = Field(
        ...,
        description="The actual script content including dialogue and action directions",
    )

    class Config:
        schema_extra = {
            "example": {
                "description": "The detective confronts the suspect",
                "setting": "INT. INTERROGATION ROOM - NIGHT",
                "script_content": (
                    "DETECTIVE JOHNSON\n"
                    "(firmly)\n"
                    "Where were you on the night of the 15th?\n\n"
                    "SUSPECT\n"
                    "(nervously)\n"
                    "I was at home, I swear.\n\n"
                    "Detective Johnson slams his fist on the table.\n\n"
                    "DETECTIVE JOHNSON\n"
                    "We have witnesses!"
                ),
            }
        }


class MovieScript(BaseModel):
    """
    Model representing a complete movie script.

    Attributes:
        title: The title of the movie
        genre: The genre(s) of the movie
        logline: A one-sentence summary of the plot
        scenes: List of scenes in the movie
    """

    title: str = Field(..., description="The title of the movie")
    genre: str = Field(
        ..., description="The genre(s) of the movie (e.g., 'Action/Thriller')"
    )
    logline: str = Field(..., description="A one-sentence summary of the plot")
    scenes: List[Scene] = Field(
        ..., description="List of scenes in the movie", min_items=1
    )

    # Optional fields
    target_audience: Optional[str] = Field(
        None, description="Target audience for the movie (e.g., 'PG-13', 'Adult')"
    )
    screenplay_author: Optional[str] = Field(
        None, description="Name of the screenplay author"
    )

    class Config:
        schema_extra = {
            "example": {
                "title": "The Last Clue",
                "genre": "Mystery/Thriller",
                "logline": "A retired detective must solve one last case when his arch-nemesis returns.",
                "scenes": [
                    {
                        "description": "Detective Johnson receives a mysterious package",
                        "setting": "EXT. SUBURBAN HOME - MORNING",
                        "script_content": (
                            "A mail carrier drops off a package at the door.\n\n"
                            "JOHNSON opens the door, picks up the package. His face turns pale as he reads the return address.\n\n"
                            "JOHNSON\n"
                            "(whispers)\n"
                            "He's back."
                        ),
                    }
                ],
                "target_audience": "PG-13",
                "screenplay_author": "A. Writer",
            }
        }
