"""
"""
    """Abstract base class for memory implementations."""
        """
        """
        """
        """
        """
        """
        """
        """
    async def search(self, field: str, value: Any, operator: str = "==", limit: int = 10) -> List[Dict[str, Any]]:
        """
        """
        """
        """
        """
        """
        """
        """
        """
        """
        """
        """