storage:
  type: gcp-firestore
  project: cherry-ai-project
  collection: agent_sessions

monitoring:
  enabled: true
  provider: vertex-ai
  service_account: vertex-agent@cherry-ai-project.iam.gserviceaccount.com

tools:
  - type: portkey
    api_key_secret: projects/cherry-ai-project/secrets/portkey-api-key