global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "orchestra-api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["orchestra-api:8000"]

  - job_name: "llm-test-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["llm-test-service:8001"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
