"""
"""
    """Base exception for all LLM provider errors."""
    """Error connecting to the LLM provider service."""
    """Authentication failure with the LLM provider."""
    """Rate limit exceeded for the LLM provider."""
    """Resource exhausted (e.g., token quota) for the LLM provider."""
    """Invalid request parameters sent to the LLM provider."""
    """Internal server error from the LLM provider."""
    """Request to the LLM provider timed out."""
    """Error related to the specific model requested."""