"""
"""
    """
    """
        """Generate content hash if not provided."""
    """
    """
        """
        """
        """
        """
        """
        """
        """
        """
        """
        """
        """
        """
        """Get list of supported file formats."""
        """Get list of content types this parser produces."""