name: admin-ui-site
description: Pulumi stack for Admin UI static site
runtime:
  name: python
  options:
    toolchain: pip
    virtualenv: venv
config:
  pulumi:tags:
    value:
      pulumi:template: gcp-python
