apiVersion: v1
kind: Service
metadata:
  name: orchestra-service
  namespace: default
  labels:
    app: orchestra
    environment: production
spec:
  selector:
    app: orchestra
    environment: production
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP