apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestra-app
  namespace: default
  labels:
    app: orchestra
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orchestra
      environment: staging
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: orchestra
        environment: staging
    spec:
      containers:
      - name: orchestra-app
        image: ${DOCKERHUB_USERNAME}/orchestra:develop
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: ENVIRONMENT
          value: "staging"
        - name: PORT
          value: "8000"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/app/gcp-credentials.json"
        volumeMounts:
        - name: gcp-credentials
          mountPath: /app/gcp-credentials.json
          subPath: gcp-credentials.json
          readOnly: true
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
      volumes:
      - name: gcp-credentials
        secret:
          secretName: gcp-credentials