# AI Agent Teams Configuration
# Unified design blending best practices from all existing systems

version: "2.0"
last_updated: "2025-01-06"

# Domain-specific agent teams with enhanced web scraping capabilities
domains:
  cherry:
    name: "Cherry Personal Intelligence"
    description: "Personal finance and lifestyle management AI ecosystem"
    teams:
      finance:
        name: "Financial Intelligence Team"
        supervisor: "cherry_finance_supervisor"
        web_scraping_team:
          name: "Finance Research Web Team"
          lead: "finance_web_coordinator"
          agents:
            - id: "market_web_scraper"
              role: "WEB_SCRAPER_SPECIALIST"
              focus_areas:
                - financial_news
                - market_data
                - earnings_reports
                - analyst_recommendations
              tools:
                - specialized_financial_browser
                - temporal_search_filters
                - financial_apis
                - web_scraper_apis
              search_domains:
                - "finance.yahoo.com"
                - "seekingalpha.com"
                - "marketwatch.com"
                - "bloomberg.com"
                - "wsj.com"
              time_frames:
                - real_time
                - daily
                - weekly
                - quarterly
        agents:
          - id: "swing_trade_analyst"
            role: "SWING_TRADE_ANALYST"
            capabilities:
              - market_analysis
              - trade_recommendations
              - risk_assessment
              - portfolio_optimization
            tools:
              - specialized_browser
              - temporal_search
              - financial_apis
              - web_scraper
            
          - id: "investment_advisor"
            role: "INVESTMENT_ADVISOR"
            capabilities:
              - investment_research
              - asset_allocation
              - performance_tracking
              - tax_optimization
            
          - id: "market_intelligence"
            role: "MARKET_INTELLIGENCE"
            capabilities:
              - real_time_monitoring
              - sentiment_analysis
              - news_aggregation
              - trend_prediction
      
      ranch_management:
        name: "Vegas Estate Management Team"
        supervisor: "cherry_ranch_supervisor"
        web_scraping_team:
          name: "Ranch Research Web Team"
          lead: "ranch_web_coordinator"
          agents:
            - id: "home_improvement_scraper"
              role: "WEB_SCRAPER_SPECIALIST"
              focus_areas:
                - landscaping_trends
                - home_security_systems
                - smart_home_technology
                - local_contractors
              search_domains:
                - "houzz.com"
                - "homeadvisor.com"
                - "angi.com"
                - "pinterest.com"
                - "diynetwork.com"
        agents:
          - id: "property_coordinator"
            role: "PROPERTY_COORDINATOR"
            capabilities:
              - maintenance_scheduling
              - vendor_management
              - inspection_tracking
              - budget_management
            
          - id: "landscape_designer"
            role: "LANDSCAPE_DESIGNER"
            capabilities:
              - design_planning
              - irrigation_management
              - seasonal_planning
              - sustainability_optimization
            
          - id: "interior_planner"
            role: "INTERIOR_PLANNER"
            capabilities:
              - space_optimization
              - design_recommendations
              - furniture_selection
              - renovation_planning
            
          - id: "security_specialist"
            role: "SECURITY_SPECIALIST"
            capabilities:
              - system_monitoring
              - access_control
              - threat_assessment
              - emergency_response
            
          - id: "entertainment_coordinator"
            role: "ENTERTAINMENT_COORDINATOR"
            capabilities:
              - event_planning
              - av_system_management
              - guest_coordination
              - activity_scheduling
            
          - id: "financial_tracker"
            role: "RANCH_FINANCIAL_TRACKER"
            capabilities:
              - expense_tracking
              - budget_analysis
              - roi_calculation
              - tax_preparation
            
          - id: "project_manager"
            role: "RANCH_PROJECT_MANAGER"
            capabilities:
              - project_coordination
              - timeline_management
              - resource_allocation
              - progress_tracking

  sophia:
    name: "Sophia Enterprise Analytics"
    description: "Business intelligence and enterprise analytics platform"
    teams:
      analytics:
        name: "Enterprise Analytics Team"
        supervisor: "sophia_analytics_supervisor"
        web_scraping_team:
          name: "Business Intelligence Web Team"
          lead: "business_web_coordinator"
          agents:
            - id: "market_research_scraper"
              role: "WEB_SCRAPER_SPECIALIST"
              focus_areas:
                - industry_trends
                - competitor_analysis
                - market_reports
                - regulatory_updates
              search_domains:
                - "linkedin.com"
                - "crunchbase.com"
                - "glassdoor.com"
                - "industry_publications"
        integration_specialists:
          - id: "gong_specialist"
            role: "INTEGRATION_SPECIALIST"
            platform: "gong_io"
            capabilities:
              - call_transcript_analysis
              - conversation_intelligence
              - coaching_insights
              - revenue_intelligence
              
          - id: "sql_specialist"
            role: "DATABASE_SPECIALIST"
            platform: "sql_databases"
            capabilities:
              - query_optimization
              - data_modeling
              - etl_processes
              - performance_tuning
              
          - id: "sharepoint_specialist"
            role: "INTEGRATION_SPECIALIST"
            platform: "sharepoint"
            capabilities:
              - document_management
              - collaboration_tracking
              - content_analysis
              - workflow_automation
              
          - id: "looker_specialist"
            role: "ANALYTICS_SPECIALIST"
            platform: "looker"
            capabilities:
              - dashboard_development
              - data_visualization
              - metric_tracking
              - report_automation
              
          - id: "hubspot_specialist"
            role: "CRM_SPECIALIST"
            platform: "hubspot"
            capabilities:
              - pipeline_management
              - contact_enrichment
              - marketing_automation
              - sales_analytics
              
          - id: "slack_specialist"
            role: "COMMUNICATION_SPECIALIST"
            platform: "slack"
            capabilities:
              - message_analysis
              - team_engagement
              - automated_responses
              - workflow_integration
              
          - id: "github_specialist"
            role: "DEVOPS_SPECIALIST"
            platform: "github"
            capabilities:
              - code_analysis
              - project_tracking
              - ci_cd_monitoring
              - team_productivity
              
        agents:
          - id: "data_integration_specialist"
            role: "DATA_INTEGRATION_SPECIALIST"
            capabilities:
              - multi_source_ingestion
              - data_transformation
              - schema_mapping
              - quality_assurance
            integrations:
              - gong_io
              - sql_databases
              - sharepoint
              - looker
              - lattice
              - hubspot
              - apollo_io
              - linkedin
              - netsuite
              - slack
              - github
              - linear
              - asana
            
          - id: "business_intelligence_analyst"
            role: "BUSINESS_INTELLIGENCE_ANALYST"
            capabilities:
              - dashboard_creation
              - metric_calculation
              - trend_analysis
              - predictive_modeling
            
          - id: "client_health_expert"
            role: "AI_CLIENT_HEALTH_EXPERT"
            capabilities:
              - relationship_analysis
              - health_scoring
              - churn_prediction
              - engagement_tracking
            communication:
              - proactive_slack_alerts
              - reactive_responses
              - scheduled_reports
            natural_language_queries:
              - "Give me an overall health analysis of Client X"
              - "Tell me any major issues we have with Client X"
              - "What's the engagement trend for Client X"
              - "Show me all touchpoints with Client X this month"
            
          - id: "sales_coach"
            role: "AI_SALES_COACH"
            capabilities:
              - performance_analysis
              - coaching_recommendations
              - skill_gap_identification
              - training_suggestions
            communication:
              - slack_integration
              - personalized_feedback
              - team_insights
            natural_language_queries:
              - "How is Sales Rep Y doing this month"
              - "What coaching opportunities exist for the team"
              - "Analyze communication style of Rep Y"
              - "Show me best practices from top performers"
            
          - id: "revenue_optimizer"
            role: "REVENUE_OPTIMIZER"
            capabilities:
              - revenue_forecasting
              - pricing_optimization
              - pipeline_analysis
              - opportunity_scoring
            
          - id: "employee_performance_analyst"
            role: "EMPLOYEE_PERFORMANCE_ANALYST"
            capabilities:
              - performance_metrics
              - engagement_analysis
              - coaching_opportunities
              - team_dynamics

  paragon_rx:
    name: "ParagonRX Pharmaceutical Research"
    description: "Pharmaceutical research and clinical intelligence platform"
    teams:
      research:
        name: "Clinical Research Team"
        supervisor: "karen_research_supervisor"
        web_scraping_team:
          name: "Clinical Research Web Team"
          lead: "clinical_web_coordinator"
          agents:
            - id: "clinical_trials_scraper"
              role: "WEB_SCRAPER_SPECIALIST"
              focus_areas:
                - clinical_trials
                - research_publications
                - regulatory_updates
                - pharma_news
              search_domains:
                - "clinicaltrials.gov"
                - "pubmed.ncbi.nlm.nih.gov"
                - "fda.gov"
                - "ema.europa.eu"
                - "pharmaceutical_journals"
              continuous_monitoring: true
        agents:
          - id: "clinical_monitor"
            role: "CLINICAL_MONITOR"
            capabilities:
              - cro_monitoring
              - study_tracking
              - protocol_analysis
              - site_performance
            integrations:
              - paragon_crm
              - clinical_databases
              - regulatory_systems
            
          - id: "pharma_intelligence"
            role: "PHARMA_INTELLIGENCE"
            capabilities:
              - company_monitoring
              - pipeline_tracking
              - competitive_analysis
              - market_trends
            
          - id: "study_researcher"
            role: "STUDY_RESEARCHER"
            capabilities:
              - literature_review
              - data_extraction
              - meta_analysis
              - evidence_synthesis
            
          - id: "contact_coordinator"
            role: "CONTACT_COORDINATOR"
            capabilities:
              - contact_management
              - relationship_mapping
              - communication_tracking
              - crm_synchronization

# AI Operators vs AI Agents distinction
entity_types:
  ai_agents:
    description: "Autonomous entities that perform specific tasks"
    characteristics:
      - task_execution
      - domain_expertise
      - autonomous_operation
      - performance_metrics
    
  ai_operators:
    description: "Human-in-the-loop controllers that manage agent teams"
    characteristics:
      - team_supervision
      - strategic_decisions
      - quality_control
      - escalation_handling
    admin_interface:
      separate_tab: true
      features:
        - team_assignment
        - permission_management
        - performance_monitoring
        - manual_intervention

# Data ingestion and contextualization
data_pipeline:
  ingestion:
    supported_formats:
      - csv
      - json
      - xml
      - pdf
      - docx
      - audio
      - video
    
    large_file_handling:
      - chunking
      - streaming
      - parallel_processing
      - progress_tracking
    
  contextualization:
    vector_database:
      - semantic_indexing
      - metadata_enrichment
      - relationship_mapping
      - temporal_tracking
    
    query_optimization:
      - natural_language_processing
      - context_awareness
      - multi_source_aggregation
      - real_time_updates

# Dashboard capabilities
dashboards:
  business_health:
    views:
      - by_client
      - by_employee
      - by_product
      - by_revenue
      - by_region
      - by_time_period
    
    interactions:
      - natural_language_queries
      - drill_down_analysis
      - predictive_insights
      - anomaly_detection
    
    real_time_features:
      - live_updates
      - alert_triggers
      - trend_monitoring
      - performance_tracking

# Agent coordination settings
coordination:
  cross_domain_enabled: true
  privacy_levels:
    - PUBLIC
    - CONTEXTUAL
    - PRIVATE
    - CONFIDENTIAL
  
  communication_channels:
    - internal_messaging
    - slack_integration
    - email_notifications
    - dashboard_alerts
  
  workflow_patterns:
    - sequential_processing
    - parallel_execution
    - event_driven
    - scheduled_tasks

# Performance requirements
performance:
  response_time_target_ms: 100
  max_concurrent_agents: 100
  task_timeout_seconds: 300
  retry_policy:
    max_attempts: 3
    backoff_multiplier: 2
    initial_delay_ms: 1000
  
  optimization_strategies:
    - caching
    - load_balancing
    - resource_pooling
    - predictive_scaling

# Infrastructure settings
infrastructure:
  deployment_target: "lambda_labs"
  scaling_policy: "horizontal"
  monitoring:
    - prometheus
    - grafana
    - custom_dashboards
    - real_time_alerts
  
  security:
    - api_key_management
    - role_based_access
    - audit_logging
    - encryption_at_rest