# This file will store configurations for user-defined MCP server instances.
# It should be a list of UserDefinedMCPServerInstanceConfig objects in YAML format.
# Example of an empty list:
# []
# Example of a single entry (ensure fields match UserDefinedMCPServerInstanceConfig model):
# - id: "uuid_here"
#   name: "My Test Server"
#   description: "A test MCP server instance"
#   target_ai_coders: ["RooCoder", "OpenAI_GPT4"]
#   enabled_internal_tools: ["copilot"]
#   copilot_config_override:
#     some_copilot_setting: "value"
#   base_docker_image: "mcp_server:dev"
#   resources:
#     cpu: "2"
#     memory: "4Gi"
#   custom_environment_variables:
#     MY_CUSTOM_VAR: "my_value"
#   ai_providers:
#     - name: "openai"
#       api_key_secret_name: "OPENAI_API_KEY_FOR_SERVER_1" # Name of env var or secret
#       model: "gpt-4-turbo-preview"
#   context_sources:
#     - type: "git_repo"
#       uri: "https://github.com/example/my_code_repo.git"
#       branch: "main"
#       paths: ["src/"]
#   generated_mcp_internal_config_yaml: |
#     storage:
#       type: in_memory
#       max_entries: 10000
#       ttl_seconds: 86400
#     copilot:
#       enabled: true
#       some_copilot_setting: "value" # Example override
#       api_key: null
#     debug: false
#     log_level: INFO
#     port: 9000
#     host: "0.0.0.0"
#     servers: {}
#   desired_status: "running"
#   created_at: "2023-01-01T12:00:00Z" # ISO format datetime
#   updated_at: "2023-01-01T12:00:00Z" # ISO format datetime

[]
