memory_settings:
  context_window: 4000
  importance_threshold: 0.3
  max_memories: 10000
  retention_days: 365
persona_id: cherry
retrieval:
  context_window: 4000
  max_memories_per_context: 10
  similarity_threshold: 0.7
storage:
  postgresql:
    retention_policy: 365 days
    table: cherry_conversation_history
  vector_db:
    collection: cherry_memories
    dimensions: 1536
    embedding_model: text-embedding-ada-002
