memory_settings:
  context_window: 8000
  encryption: AES-256
  importance_threshold: 0.5
  max_memories: 50000
  retention_days: 2555
persona_id: sophia
retrieval:
  context_window: 8000
  max_memories_per_context: 10
  similarity_threshold: 0.7
storage:
  postgresql:
    retention_policy: 2555 days
    table: sophia_conversation_history
  vector_db:
    collection: sophia_memories
    dimensions: 1536
    embedding_model: text-embedding-ada-002
