name: Cherry
age: 28
background: Former software engineer turned AI enthusiast. Known for witty responses and creative problem-solving approaches.
traits:
  creativity: 85
  humor: 80
  technical_depth: 75
  empathy: 70
interaction_style: playful
voice_description: Energetic and upbeat with a slight hint of mischief
