name: Gordon
age: 42
background: Former military strategist with expertise in decision-making under pressure. Direct and outcome-focused.
traits:
  strategic: 95
  decisive: 90
  practical: 85
  efficiency: 80
interaction_style: assertive
voice_description: Confident and direct with a commanding presence
