#!/bin/bash
# Domain Migration Script
# Generated by Domain Separation Analyzer

# Create domain directories
mkdir -p domains/{Personal,PayReady,ParagonRX}/{services,models,api,config}

# Migrate Personal files
# mv agent/app/routers/llm.py domains/Personal/services/
# mv agent/app/routers/data_ingestion.py domains/Personal/services/
# mv agent/app/routers/natural_language.py domains/Personal/services/
# mv agent/app/routers/llm_orchestration.py domains/Personal/services/
# mv agent/app/routers/suggestions.py domains/Personal/services/

# Migrate Personal files
# mv agent/app/services/specialized_agents.py domains/Personal/services/
# mv agent/app/services/audit_log.py domains/Personal/services/
# mv agent/app/services/agent_orchestrator.py domains/Personal/services/

# Migrate Personal files
# mv ai_components/claude/claude_analyzer.py domains/Personal/services/

# Migrate Personal files
# mv ai_components/orchestration/vultr_autoscaling.py domains/Personal/services/
# mv ai_components/orchestration/roo_mcp_adapter.py domains/Personal/services/
# mv ai_components/orchestration/intelligent_cache.py domains/Personal/services/
# mv ai_components/orchestration/mode_transition_manager.py domains/Personal/services/
# mv ai_components/orchestration/ai_orchestrator.py domains/Personal/services/

# Migrate Personal files
# mv ai_components/tests/test_roo_integration.py domains/Personal/services/

# Migrate Personal files
# mv ai_components/agents/cursor_ai_enhanced.py domains/Personal/services/
# mv ai_components/agents/claude_integration.py domains/Personal/services/

# Migrate Personal files
# mv ai_components/design/dalle_integration.py domains/Personal/services/
# mv ai_components/design/recraft_integration.py domains/Personal/services/
# mv ai_components/design/design_orchestrator.py domains/Personal/services/

# Migrate Personal files
# mv core/env_config.py domains/Personal/services/

# Migrate Personal files
# mv core/memory/config.py domains/Personal/services/
# mv core/memory/example_usage.py domains/Personal/services/

# Migrate Personal files
# mv core/infrastructure/deployment/base.py domains/Personal/services/

# Migrate Personal files
# mv core/utils/pydantic_validators.py domains/Personal/services/

# Migrate Personal files
# mv core/api/models/requests.py domains/Personal/services/

# Migrate Personal files
# mv core/api/endpoints/conversation.py domains/Personal/services/

# Migrate Personal files
# mv core/orchestrator/examples/llm_client.py domains/Personal/services/
# mv core/orchestrator/examples/llm_demo.py domains/Personal/services/
# mv core/orchestrator/examples/persona_client.py domains/Personal/services/

# Migrate Personal files
# mv core/orchestrator/src/main_simple.py domains/Personal/services/

# Migrate Personal files
# mv core/orchestrator/src/memory/integration.py domains/Personal/services/

# Migrate Personal files
# mv core/orchestrator/src/memory/lifecycle/importance_scorer.py domains/Personal/services/

# Migrate Personal files
# mv core/orchestrator/src/memory/retrieval/query_classifier.py domains/Personal/services/

# Migrate Personal files
# mv core/orchestrator/src/core/agents.py domains/Personal/services/
# mv core/orchestrator/src/core/orchestrator.py domains/Personal/services/
# mv core/orchestrator/src/core/main.py domains/Personal/services/
# mv core/orchestrator/src/core/memory.py domains/Personal/services/

# Migrate Personal files
# mv core/orchestrator/src/api/dependencies/prompt_builder.py domains/Personal/services/

# Migrate Personal files
# mv core/orchestrator/src/api/endpoints/interaction.py domains/Personal/services/
# mv core/orchestrator/src/api/endpoints/monitoring.py domains/Personal/services/
# mv core/orchestrator/src/api/endpoints/llm_interaction.py domains/Personal/services/
# mv core/orchestrator/src/api/endpoints/phidata_chat.py domains/Personal/services/
# mv core/orchestrator/src/api/endpoints/auth.py domains/Personal/services/

# Migrate Personal files
# mv core/orchestrator/src/api/middleware/persona_loader.py domains/Personal/services/

# Migrate Personal files
# mv core/orchestrator/src/agents/persona_agent.py domains/Personal/services/
# mv core/orchestrator/src/agents/simplified_agent_registry.py domains/Personal/services/
# mv core/orchestrator/src/agents/llm_agent.py domains/Personal/services/
# mv core/orchestrator/src/agents/messaging_agent.py domains/Personal/services/
# mv core/orchestrator/src/agents/__init__.py domains/Personal/services/

# Migrate Personal files
# mv core/orchestrator/src/agents/examples/agent_usage_example.py domains/Personal/services/
# mv core/orchestrator/src/agents/examples/pubsub_agent_example.py domains/Personal/services/

# Migrate Personal files
# mv core/orchestrator/src/agents/memory/models.py domains/Personal/services/
# mv core/orchestrator/src/agents/memory/layered_memory.py domains/Personal/services/

# Migrate Personal files
# mv core/orchestrator/src/agents/teams/coordinator.py domains/Personal/services/

# Migrate Personal files
# mv core/orchestrator/src/resilience/incident_reporter.py domains/Personal/services/
# mv core/orchestrator/src/resilience/tasks.py domains/Personal/services/

# Migrate Personal files
# mv core/orchestrator/src/personas/loader.py domains/Personal/services/
# mv core/orchestrator/src/personas/enhanced_persona_manager.py domains/Personal/services/

# Migrate Personal files
# mv core/orchestrator/src/llm/litellm_client.py domains/Personal/services/

# Migrate Personal files
# mv core/orchestrator/src/config/models.py domains/Personal/services/
# mv core/orchestrator/src/config/personas.yaml domains/Personal/services/

# Migrate Personal files
# mv core/orchestrator/src/tools/registry.py domains/Personal/services/

# Migrate Personal files
# mv core/orchestrator/src/services/interaction_service.py domains/Personal/services/
# mv core/orchestrator/src/services/enhanced_agent_orchestrator.py domains/Personal/services/
# mv core/orchestrator/src/services/conversation_service.py domains/Personal/services/
# mv core/orchestrator/src/services/agent_orchestrator.py domains/Personal/services/
# mv core/orchestrator/src/services/base_orchestrator.py domains/Personal/services/

# Migrate Personal files
# mv core/orchestrator/src/services/llm/providers.py domains/Personal/services/

# Migrate Personal files
# mv core/agents/retriever_agent.py domains/Personal/services/

# Migrate Personal files
# mv core/business/workflows/examples.py domains/Personal/services/

# Migrate Personal files
# mv core/business/llm/provider.py domains/Personal/services/

# Migrate Personal files
# mv core/personas/models.py domains/Personal/services/
# mv core/personas/personas_detailed.yaml domains/Personal/services/
# mv core/personas/test_models.py domains/Personal/services/

# Migrate Personal files
# mv core/data_ingestion/deduplication/duplicate_resolver.py domains/Personal/services/
# mv core/data_ingestion/deduplication/audit_logger.py domains/Personal/services/

# Migrate Personal files
# mv core/data_ingestion/interfaces/parser.py domains/Personal/services/

# Migrate Personal files
# mv core/data_ingestion/parsers/slack_parser.py domains/Personal/services/

# Migrate Personal files
# mv core/data_ingestion/storage/postgres_adapter.py domains/Personal/services/
# mv core/data_ingestion/storage/weaviate_adapter.py domains/Personal/services/

# Migrate Personal files
# mv core/monitoring/claude_monitor.py domains/Personal/services/
# mv core/monitoring/monitored_litellm_client.py domains/Personal/services/

# Migrate Personal files
# mv core/persistency/mode_config_persistence.py domains/Personal/services/

# Migrate Personal files
# mv core/services/agents/examples.py domains/Personal/services/
# mv core/services/agents/base.py domains/Personal/services/

# Migrate Personal files
# mv core/auth/__init__.py domains/Personal/services/
# mv core/auth/simple_auth.py domains/Personal/services/

# Migrate Personal files
# mv factory_integration/cache_manager.py domains/Personal/services/

# Migrate Personal files
# mv factory_integration/tests/test_cache_manager.py domains/Personal/services/

# Migrate Personal files
# mv factory_integration/config/context.yaml domains/Personal/services/

# Migrate PayReady files
# mv agent/app/services/natural_language_processor.py domains/PayReady/services/

# Migrate PayReady files
# mv services/pay_ready/etl_orchestrator.py domains/PayReady/services/
# mv services/pay_ready/entity_resolver.py domains/PayReady/services/
# mv services/pay_ready/__init__.py domains/PayReady/services/
# mv services/pay_ready/memory_manager.py domains/PayReady/services/
# mv services/pay_ready/query_agent.py domains/PayReady/services/

# Migrate PayReady files
# mv core/memory/implementations/storage/postgresql.py domains/PayReady/services/

# Migrate PayReady files
# mv core/infrastructure/connectivity/dragonfly.py domains/PayReady/services/

# Migrate PayReady files
# mv workflows/pay_ready_etl_flow.py domains/PayReady/services/

# Migrate ParagonRX files
# mv agent/tests/test_personas_admin.py domains/ParagonRX/services/

# Migrate ParagonRX files
# mv agent/app/main.py domains/ParagonRX/services/

# Migrate ParagonRX files
# mv agent/app/routers/automation.py domains/ParagonRX/services/
# mv agent/app/routers/personas_admin.py domains/ParagonRX/services/
# mv agent/app/routers/system.py domains/ParagonRX/services/

# Migrate ParagonRX files
# mv agent/app/services/system_health.py domains/ParagonRX/services/
# mv agent/app/services/automation.py domains/ParagonRX/services/

# Migrate ParagonRX files
# mv ai_components/orchestrator_cli_enhanced.py domains/ParagonRX/services/

# Migrate ParagonRX files
# mv ai_components/orchestration/unified_api_router.py domains/ParagonRX/services/

# Migrate ParagonRX files
# mv ai_components/cursor_ai/cursor_integration_enhanced.py domains/ParagonRX/services/

# Migrate ParagonRX files
# mv core/health_monitor.py domains/ParagonRX/services/
# mv core/config.py domains/ParagonRX/services/
# mv core/main.py domains/ParagonRX/services/
# mv core/llm_types.py domains/ParagonRX/services/

# Migrate ParagonRX files
# mv core/memory/interfaces.py domains/ParagonRX/services/

# Migrate ParagonRX files
# mv core/infrastructure/connectivity/mongodb.py domains/ParagonRX/services/
# mv core/infrastructure/connectivity/base.py domains/ParagonRX/services/

# Migrate ParagonRX files
# mv core/api/main.py domains/ParagonRX/services/

# Migrate ParagonRX files
# mv core/api/models/responses.py domains/ParagonRX/services/

# Migrate ParagonRX files
# mv core/orchestrator/src/main.py domains/ParagonRX/services/

# Migrate ParagonRX files
# mv core/orchestrator/src/api/app.py domains/ParagonRX/services/

# Migrate ParagonRX files
# mv core/orchestrator/src/api/dependencies/cache.py domains/ParagonRX/services/
# mv core/orchestrator/src/api/dependencies/memory.py domains/ParagonRX/services/

# Migrate ParagonRX files
# mv core/orchestrator/src/api/endpoints/health.py domains/ParagonRX/services/

# Migrate ParagonRX files
# mv core/data_ingestion/interfaces/storage.py domains/ParagonRX/services/

# Migrate ParagonRX files
# mv core/llm/unified_router.py domains/ParagonRX/services/

# Migrate ParagonRX files
# mv core/config/unified_config.py domains/ParagonRX/services/
# mv core/config/__init__.py domains/ParagonRX/services/

# Migrate ParagonRX files
# mv core/services/memory/unified_memory.py domains/ParagonRX/services/
# mv core/services/memory/base.py domains/ParagonRX/services/

