# MCP Performance Configuration

# Connection pooling settings
connection_pools:
  redis:
    max_connections: 100
    min_idle: 10
    max_idle: 50
    connection_timeout: 5000  # ms
    socket_timeout: 5000      # ms
    retry_on_timeout: true
    
  firestore:
    max_concurrent_requests: 50
    max_retries: 3
    timeout: 30000  # ms
    
  qdrant:
    max_connections: 20
    timeout: 10000  # ms
    grpc_compression: true

# Caching configuration
caching:
  health_check:
    ttl: 30  # seconds
    max_size: 100
    
  memory_queries:
    ttl: 300  # seconds
    max_size: 1000
    
  secret_values:
    ttl: 600  # seconds
    max_size: 500
    encrypt: true

# Request limits
rate_limiting:
  enabled: true
  requests_per_minute: 1000
  burst_size: 100
  
  per_endpoint:
    "/mcp/deploy": 10
    "/mcp/create_secret": 50
    "/mcp/store_memory": 500
    "/mcp/query_memory": 1000

# Performance monitoring
monitoring:
  metrics:
    enabled: true
    collection_interval: 10  # seconds
    
  profiling:
    enabled: false
    sample_rate: 0.01
    
  tracing:
    enabled: true
    sample_rate: 0.1
    export_to: "jaeger"

# Resource limits
resources:
  memory:
    max_heap_size: "2G"
    reserved_memory: "512M"
    
  cpu:
    worker_processes: 4
    threads_per_worker: 2
    
  io:
    max_open_files: 10000
    socket_backlog: 128

# Optimization settings
optimizations:
  # Batch processing
  batching:
    enabled: true
    max_batch_size: 100
    batch_timeout: 100  # ms
    
  # Query optimization
  query_optimization:
    use_indexes: true
    parallel_queries: true
    max_parallel: 10
    
  # Memory optimization
  memory_optimization:
    gc_interval: 300  # seconds
    compress_responses: true
    use_msgpack: true
    
  # Network optimization
  network_optimization:
    tcp_nodelay: true
    keep_alive: true
    keep_alive_timeout: 30
    
# Async processing
async_processing:
  event_loop_policy: "uvloop"
  max_concurrent_tasks: 1000
  task_timeout: 300  # seconds
  
# Database optimizations
database:
  connection_recycling: 3600  # seconds
  statement_cache_size: 1000
  prefetch_size: 100
  
# Security performance
security:
  auth_cache_ttl: 300  # seconds
  token_validation_cache: true
  parallel_auth_checks: true