context:
  storage:
    postgres:
      connection_string: ${POSTGRES_CONNECTION_STRING}
      enabled: true
      pool_size: 10
    redis:
      db: 0
      enabled: true
      url: ${REDIS_URL}
    type: hybrid
    weaviate:
      api_key: ${WEAVIATE_API_KEY}
      enabled: true
      url: ${WEAVIATE_URL}
  synchronization:
    batch_size: 100
    enabled: true
    interval: 30
droids:
  architect:
    capabilities:
    - system_design
    - architecture_planning
    - integration_design
    enabled: true
    max_tokens: 4096
    mcp_mapping: conductor_server
    model: factory-architect-v1
    temperature: 0.7
  code:
    capabilities:
    - code_generation
    - refactoring
    - optimization
    enabled: true
    max_tokens: 8192
    mcp_mapping: tools_server
    model: factory-code-v1
    temperature: 0.3
  debug:
    capabilities:
    - error_analysis
    - debugging
    - performance_profiling
    enabled: true
    max_tokens: 4096
    mcp_mapping: tools_server
    model: factory-debug-v1
    temperature: 0.1
  knowledge:
    capabilities:
    - documentation
    - knowledge_management
    - context_retrieval
    enabled: true
    max_tokens: 4096
    mcp_mapping: memory_server
    model: factory-knowledge-v1
    temperature: 0.5
  reliability:
    capabilities:
    - deployment
    - monitoring
    - infrastructure
    enabled: true
    max_tokens: 4096
    mcp_mapping: deployment_server
    model: factory-reliability-v1
    temperature: 0.2
environment: development
factory_ai:
  api_key: ${FACTORY_AI_API_KEY}
  base_url: https://api.factoryai.com/v1
  max_retries: 3
  retry_delay: 1.0
  timeout: 30
infrastructure:
  pulumi:
    backend: file://./pulumi
    passphrase: ${PULUMI_CONFIG_PASSPHRASE}
    stack: factory-ai-integration
  vultr:
    api_key: ${VULTR_API_KEY}
    instance_type: vc2-2c-4gb
    region: ewr
mcp_integration:
  discovery_endpoint: http://localhost:8010/discover
  enabled: true
  servers:
    factory-architect:
      cache_settings:
        strategy: lfu
        ttl: 7200
      mcp_servers:
      - conductor
      - memory
      - code-intelligence
      - deployment
      rate_limits:
        requests_per_minute: 60
      routing_rules:
        architecture_planning: memory
        code_structure: code-intelligence
        deployment_planning: deployment
        system_design: conductor
    factory-code:
      cache_settings:
        strategy: lru
        ttl: 1800
      mcp_servers:
      - code-intelligence
      - git-intelligence
      - tools
      - memory
      rate_limits:
        requests_per_minute: 100
      routing_rules:
        code_context: git-intelligence
        code_generation: code-intelligence
        optimization: tools
        refactoring: code-intelligence
    factory-debug:
      cache_settings:
        strategy: lru
        ttl: 900
      mcp_servers:
      - tools
      - code-intelligence
      - git-intelligence
      - memory
      rate_limits:
        requests_per_minute: 80
      routing_rules:
        debugging: tools
        error_analysis: code-intelligence
        error_history: git-intelligence
        performance_profiling: tools
monitoring:
  logging:
    format: json
    level: INFO
    output: stdout
  prometheus:
    enabled: true
    path: /metrics
    port: 9090
  tracing:
    enabled: true
    jaeger_endpoint: ${JAEGER_ENDPOINT}
    service_name: factory-ai-bridge
performance:
  cache:
    enabled: true
    eviction_policy: lru
    max_size: 1000
    ttl: 3600
  circuit_breaker:
    enabled: true
    failure_threshold: 5
    half_open_requests: 3
    recovery_timeout: 60
  rate_limiting:
    burst_size: 10
    enabled: true
    requests_per_minute: 60
security:
  audit:
    enabled: true
    log_all_requests: false
    sensitive_data_masking: true
  authentication:
    enabled: true
    header_name: X-Factory-API-Key
    type: api_key
  encryption:
    algorithm: AES-256-GCM
    enabled: true
    key_rotation_days: 30
version: 1.0.0
