name: Deploy AI Model

on:
  push:
    branches: [ main ]
    paths:
      - 'model/**'
      - 'training/**'
  workflow_dispatch:

env:
  PROJECT_ID: cherry-ai.me
  PROJECT_NUMBER: 525398941159
  REGION: us-central1
  REGISTRY: us-central1-docker.pkg.dev/cherry-ai.me/ai-models
  SERVICE_ACCOUNT: vertex-agent@cherry-ai.me.iam.gserviceaccount.com
  MODEL_BUCKET: gs://cherry-ai-me-model-artifacts

jobs:
  deploy-model:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4

    - name: Google Auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ env.SERVICE_ACCOUNT }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Upload model artifacts
      run: |
        gsutil -m cp -r ./model/* ${{ env.MODEL_BUCKET }}/models/

    - name: Deploy to Vertex AI
      run: |
        gcloud ai models upload \
          --region=${{ env.REGION }} \
          --display-name=orchestra-core \
          --artifact-uri=${{ env.MODEL_BUCKET }}/models/ \
          --container-image=${{ env.REGISTRY }}/model-server:latest
