name: CI Hygiene & Validation

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v4

      - name: Install yamllint and actionlint
        run: |
          pip install yamllint
          curl -sSL https://github.com/rhysd/actionlint/releases/latest/download/actionlint-linux-amd64.tar.gz | tar xz
          sudo mv actionlint /usr/local/bin/

      - name: Lint all workflow YAMLs
        run: |
          yamllint .github/workflows/
          find .github/workflows -name '*.yml' -exec actionlint -oneline -color < {} \;

      - name: Poetry check (gcp_migration)
        if: GITHUB.EVENT_NAME == 'pull_request'
        run: |
          if [ -f "gcp_migration/pyproject.toml" ]; then
            poetry check --directory=gcp_migration
          else
            echo "Skipping Poetry check for gcp_migration: pyproject.toml not found"
          fi

      - name: Poetry check (admin-api)
        if: GITHUB.EVENT_NAME == 'pull_request'
        run: |
          if [ -f "services/admin-api/pyproject.toml" ]; then
            poetry check --directory=services/admin-api
          else
            echo "Skipping Poetry check for services/admin-api: pyproject.toml not found"
          fi
