name: ci

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    env:
      VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DSN: ${{ secrets.POSTGRES_DSN }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Python dev requirements
        run: pip install -r requirements/dev.txt

      - name: Run pre-commit checks
        run: pre-commit run --all-files --show-diff-on-failure

      - name: Run tests (pytest)
        run: pytest -q

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install frontend dependencies
        working-directory: admin-ui
        run: npm ci

      - name: Run ESLint
        working-directory: admin-ui
        run: npx eslint . --ext .ts,.tsx

      - name: Build Admin UI
        working-directory: admin-ui
        run: npm run build

      - name: Validate docker-compose
        run: docker compose -f deploy/docker-compose.vultr.yml config --quiet

      - name: Pulumi preview
        uses: pulumi/actions@v4
        with:
          command: preview
          stack-name: vultr-dev
          work-dir: infra
