name: Cloud Build Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: cherry-ai.me
  PROJECT_NUMBER: 525398941159
  REGION: us-central1
  REGISTRY: us-central1-docker.pkg.dev/cherry-ai.me/orchestra
  SERVICE_ACCOUNT: vertex-agent@cherry-ai.me.iam.gserviceaccount.com

jobs:
  deploy:
    name: Cloud Build Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v3

    - name: Google Auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ env.SERVICE_ACCOUNT }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Submit Cloud Build
      run: |-
        gcloud builds submit . \
          --config cloudbuild.yaml \
          --region=${{ env.REGION }} \
          --substitutions=_ENV=prod,_GCP_REGION=${{ env.REGION }} \
          --timeout=30m
