name: Deploy to Lambda Labs

on:
  push:
    branches: [ main, lambda-production ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.LAMBDA_SSH_KEY }}
    
    - name: Deploy to Lambda Labs
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@150.136.94.139 << 'EOF'
        cd /opt/cherry-ai
        git pull origin main
        source venv/bin/activate
        pip install -r requirements.txt
        sudo systemctl restart cherry-ai
        sudo systemctl restart cherry-ai-bridge
        echo "✅ Deployment complete!"
        EOF
    
    - name: Health Check
      run: |
        sleep 30
        curl -f https://150.136.94.139/health || exit 1
        echo "✅ Health check passed!"
