name: Deploy to Development

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

env:
  PROJECT_ID: cherry-ai.me
  PROJECT_NUMBER: 525398941159
  REGION: us-central1
  REGISTRY: us-central1-docker.pkg.dev/cherry-ai.me/orchestra-dev
  SERVICE_ACCOUNT: vertex-agent@cherry-ai.me.iam.gserviceaccount.com
  ENVIRONMENT: dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: development
    
    steps:
    - uses: actions/checkout@v3

    - name: Google Auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ env.SERVICE_ACCOUNT }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Configure Docker
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.REGISTRY }}/api:dev .
        docker push ${{ env.REGISTRY }}/api:dev

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy orchestra-dev \
          --image=${{ env.REGISTRY }}/api:dev \
          --region=${{ env.REGION }} \
          --platform=managed \
          --service-account=${{ env.SERVICE_ACCOUNT }} \
          --set-env-vars="ENVIRONMENT=development,DEBUG=true"
