name: Deploy GCP Migration (Cloud Run, Terraform, Secret Manager)

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}
      GOOGLE_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GCP_PROJECT_AUTHENTICATION_EMAIL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: '1.8.2'

      - name: Install Python dependencies (gcp_migration)
        run: poetry install --no-interaction
        working-directory: gcp_migration

      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_PROJECT_AUTHENTICATION_EMAIL }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Deploy GCP Infrastructure
        run: |
          chmod +x ./deploy_gcp_infra.sh
          ./deploy_gcp_infra.sh

      - name: Post-deployment verification
        run: |
          gcloud info
          terraform -chdir=terraform output

      - name: Notify Success
        if: success()
        run: echo "GCP migration and deployment completed successfully."