name: Deploy Orchestra AI with v0.dev

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Lambda Labs
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        V0_API_KEY: ${{ secrets.VERCEL_V0DEV_API_KEY }}
        LAMBDA_SSH_KEY: ${{ secrets.LAMBDA_SSH_KEY }}
      run: |
        # Setup SSH
        mkdir -p ~/.ssh
        echo "$LAMBDA_SSH_KEY" > ~/.ssh/lambda_key
        chmod 600 ~/.ssh/lambda_key
        
        # Deploy with environment variables
        ssh -i ~/.ssh/lambda_key -o StrictHostKeyChecking=no ubuntu@150.136.94.139 << EOF
          cd /opt/cherry-ai
          git pull origin main
          
          # Set API keys from GitHub secrets
          echo "export OPENROUTER_API_KEY='$OPENROUTER_API_KEY'" >> ~/.bashrc
          echo "export V0_API_KEY='$V0_API_KEY'" >> ~/.bashrc
          source ~/.bashrc
          
          # Run deployment scripts
          chmod +x deploy_openrouter_key.sh deploy_v0_integration.sh
          ./deploy_openrouter_key.sh
          ./deploy_v0_integration.sh
          
          # Test deployment
          ai_assist review main.py
          ai_assist_v0 ui "test component"
        EOF 