name: Production Health Checks

on:
  schedule:
    # Every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Admin UI
        run: |
          status=$(curl -o /dev/null -s -w "%{http_code}" https://cherry-ai.me)
          echo "Admin UI status: $status"
          if [[ "$status" != "200" ]]; then
            echo "Admin UI health check failed" >&2
            exit 1
          fi
      - name: Check API
        run: |
          status=$(curl -o /dev/null -s -w "%{http_code}" https://cherry-ai.me/api/healthz || true)
          echo "API status: $status"
          if [[ "$status" != "200" ]]; then
            echo "API health check failed" >&2
            exit 1
          fi
