name: Rotate Service Account Keys

on:
  # Run on a schedule (every 30 days)
  schedule:
    - cron: '0 0 1,15 * *'  # Run on the 1st and 15th of every month
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      force_rotation:
        description: 'Force key rotation even if not needed'
        required: false
        default: false
        type: boolean

jobs:
  rotate-keys:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION || 'us-central1' }}
      KEY_ROTATION_PERIOD_DAYS: 90
      FORCE_ROTATION: ${{ github.event.inputs.force_rotation || 'false' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: 'gke-gcloud-auth-plugin'
      
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
      
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      
      - name: Set up GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
      
      - name: Create backup directory
        run: mkdir -p key_backups
      
      - name: Run key rotation script
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
        run: |
          # Set environment variables for the script
          export KEY_ROTATION_PERIOD_DAYS="${KEY_ROTATION_PERIOD_DAYS}"
          export BACKUP_DIR="./key_backups"
          export LOG_FILE="./key_rotation.log"
          
          # If force rotation is enabled, modify the script to always return true for check_key_rotation_needed
          if [ "${FORCE_ROTATION}" = "true" ]; then
            echo "Forcing key rotation..."
            sed -i 's/check_key_rotation_needed /echo "Forcing key rotation..."; return 0 #/g' scripts/rotate_service_account_keys.sh
          fi
          
          # Run the script
          ./scripts/rotate_service_account_keys.sh
      
      - name: Upload key backup as artifact
        uses: actions/upload-artifact@v4
        with:
          name: key-backups
          path: key_backups/
          retention-days: 30
      
      - name: Upload rotation log as artifact
        uses: actions/upload-artifact@v4
        with:
          name: key-rotation-log
          path: key_rotation.log
      
      - name: Clean up
        run: |
          # Remove key backups and logs
          rm -rf key_backups/
          rm -f key_rotation.log