name: Secure Deployment

on:
  push:
    branches: [ main ]
    tags: ['v*.*.*']
  workflow_dispatch:

env:
  PROJECT_ID: cherry-ai.me
  PROJECT_NUMBER: 525398941159
  REGION: us-central1
  REGISTRY: us-central1-docker.pkg.dev/cherry-ai.me/orchestra
  SERVICE_ACCOUNT: vertex-agent@cherry-ai.me.iam.gserviceaccount.com
  TF_STATE_BUCKET: tfstate-cherry-ai-me-orchestra

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Google Auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ env.SERVICE_ACCOUNT }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Run security scan
      run: |
        gcloud beta security scan images scan ${{ env.REGISTRY }}/api:latest \
          --format='json' > scan-results.json

    - name: Check scan results
      run: |
        python3 scripts/analyze_security_scan.py scan-results.json

  deploy-prod:
    needs: security-scan
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v4

    - name: Google Auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ env.SERVICE_ACCOUNT }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy orchestra-prod \
          --image=${{ env.REGISTRY }}/api:latest \
          --region=${{ env.REGION }} \
          --platform=managed \
          --service-account=${{ env.SERVICE_ACCOUNT }}