name: Setup GCP Infrastructure

on:
  workflow_dispatch:
    inputs:
      project_id:
        description: 'GCP Project ID'
        required: true
        default: 'cherry-ai-project'
        type: string
      region:
        description: 'GCP Region'
        required: true
        default: 'us-central1'
        type: string
      environment:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  setup-infrastructure:
    name: Setup GCP Infrastructure
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-cloud-aiplatform google-cloud-secret-manager google-cloud-storage
      
      - name: Set up GitHub CLI
        run: |
          type -p curl >/dev/null || (apt update && apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y
      
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      
      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      
      - name: Run setup_gcp_infrastructure.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GCP_PROJECT_ID: ${{ inputs.project_id }}
          GITHUB_ORG: 'ai-cherry'
          GITHUB_REPO: 'orchestra-main'
          REGION: ${{ inputs.region }}
          ENV: ${{ inputs.environment }}
        run: |
          chmod +x setup_gcp_infrastructure.sh
          ./setup_gcp_infrastructure.sh
      
      - name: Run update_gcp_infrastructure.sh
        env:
          GCP_MASTER_SERVICE_JSON: ${{ secrets.GCP_MASTER_SERVICE_JSON }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GCP_PROJECT_ID: ${{ inputs.project_id }}
          GITHUB_ORG: 'ai-cherry'
          GITHUB_REPO: 'orchestra-main'
          REGION: ${{ inputs.region }}
          ENV: ${{ inputs.environment }}
        run: |
          chmod +x update_gcp_infrastructure.sh
          ./update_gcp_infrastructure.sh
      
      - name: Verify infrastructure setup
        run: |
          echo "Infrastructure setup completed successfully!"
          echo "Project ID: ${{ inputs.project_id }}"
          echo "Region: ${{ inputs.region }}"
          echo "Environment: ${{ inputs.environment }}"