name: Simple CI/CD

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          pip install poetry==1.7.1
          poetry config virtualenvs.in-project true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run tests
        run: poetry run pytest tests/ -v
        continue-on-error: true  # Don't fail if no tests exist yet

      - name: Check code formatting
        run: |
          poetry run black --check . || echo "Code needs formatting"
          poetry run isort --check-only . || echo "Imports need sorting"
        continue-on-error: true

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: cherry-ai-project

      - name: Deploy to Cloud Run
        run: |
          # Build and push Docker image
          gcloud builds submit --tag gcr.io/cherry-ai-project/orchestra-api

          # Deploy to Cloud Run
          gcloud run deploy orchestra-api \
            --image gcr.io/cherry-ai-project/orchestra-api \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
        continue-on-error: true  # Don't fail the whole workflow
