name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Display file contents for debugging
      run: cat pyproject.toml
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        pip install pytest-cov==4.1.0
        
    - name: Run tests
      run: |
        export PYTHONPATH=$(pwd)
        python -m pytest tests/ --verbose --cov=core.orchestrator --cov=packages.shared --cov-report=term-missing
        
    - name: Run critical tests only
      run: |
        export PYTHONPATH=$(pwd)
        python -m pytest tests/ -m critical -v
