name: Turbo Deployment
on: [push]

jobs:
  deploy:
    runs-on: vertex-ai
    strategy:
      matrix:
        python: ["3.11"]
        region: ["us-central1"]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Auth GCP
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/525398941159/locations/global/workloadIdentityPools/github-pool/providers/github-provider
        service_account: github-actions-deployer@cherry-ai-project.iam.gserviceaccount.com

    - name: AI Code Review
      run: |
        gcloud alpha ai code-assist review \
          --source=. \
          --category=security,performance \
          --project=cherry-ai-project

    - name: Turbo Deploy
      run: |
        gcloud run deploy orchestra-prod \
          --image=us-docker.pkg.dev/cherry-ai-project/orchestra/app:latest \
          --set-env-vars=PORTKEY_API_KEY=${{ secrets.PORTKEY_API_KEY }} \
          --args=--ai-mode=turbo
