name: Update GCP Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      force_update:
        description: 'Force update of all resources'
        required: false
        default: false
        type: boolean

jobs:
  update-infrastructure:
    name: Update GCP Infrastructure
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-cloud-aiplatform google-cloud-secret-manager google-cloud-storage
      
      - name: Set up GitHub CLI
        run: |
          type -p curl >/dev/null || (apt update && apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y
      
      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      
      - name: Run update_gcp_infrastructure.sh
        env:
          GCP_MASTER_SERVICE_JSON: ${{ secrets.GCP_MASTER_SERVICE_JSON }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GITHUB_ORG: 'ai-cherry'
          GITHUB_REPO: 'orchestra-main'
          REGION: ${{ secrets.GCP_REGION }}
          ENV: ${{ inputs.environment }}
        run: |
          chmod +x update_gcp_infrastructure.sh
          ./update_gcp_infrastructure.sh
      
      - name: Verify infrastructure update
        run: |
          echo "Infrastructure update completed successfully!"
          echo "Environment: ${{ inputs.environment }}"
          echo "Force update: ${{ inputs.force_update }}"